// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calculation_sessions.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createCalculationSession = `-- name: CreateCalculationSession :one
INSERT INTO calculation_sessions (session_id, engine_version)
VALUES ($1, $2)
RETURNING id, session_id, engine_version, created_at
`

type CreateCalculationSessionParams struct {
	SessionID     uuid.UUID
	EngineVersion string
}

func (q *Queries) CreateCalculationSession(ctx context.Context, arg CreateCalculationSessionParams) (CalculationSession, error) {
	row := q.db.QueryRowContext(ctx, createCalculationSession, arg.SessionID, arg.EngineVersion)
	var i CalculationSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EngineVersion,
		&i.CreatedAt,
	)
	return i, err
}

const getCalculationSessionByID = `-- name: GetCalculationSessionByID :one
SELECT id, session_id, engine_version, created_at FROM calculation_sessions WHERE session_id = $1
`

func (q *Queries) GetCalculationSessionByID(ctx context.Context, sessionID uuid.UUID) (CalculationSession, error) {
	row := q.db.QueryRowContext(ctx, getCalculationSessionByID, sessionID)
	var i CalculationSession
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EngineVersion,
		&i.CreatedAt,
	)
	return i, err
}

const sessionExists = `-- name: SessionExists :one
SELECT EXISTS(SELECT 1 FROM calculation_sessions WHERE session_id = $1) AS exists
`

func (q *Queries) SessionExists(ctx context.Context, sessionID uuid.UUID) (bool, error) {
	row := q.db.QueryRowContext(ctx, sessionExists, sessionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
