// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calculation_events.sql

package database

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const createCalculationEvent = `-- name: CreateCalculationEvent :one
INSERT INTO calculation_events (session_id, event_type, metadata)
VALUES ($1, $2, $3)
RETURNING id, session_id, event_type, metadata, created_at
`

type CreateCalculationEventParams struct {
	SessionID uuid.UUID
	EventType string
	Metadata  json.RawMessage
}

func (q *Queries) CreateCalculationEvent(ctx context.Context, arg CreateCalculationEventParams) (CalculationEvent, error) {
	row := q.db.QueryRowContext(ctx, createCalculationEvent, arg.SessionID, arg.EventType, arg.Metadata)
	var i CalculationEvent
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.EventType,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listEventsBySession = `-- name: ListEventsBySession :many
SELECT id, session_id, event_type, metadata, created_at FROM calculation_events
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListEventsBySession(ctx context.Context, sessionID uuid.UUID) ([]CalculationEvent, error) {
	rows, err := q.db.QueryContext(ctx, listEventsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CalculationEvent
	for rows.Next() {
		var i CalculationEvent
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.EventType,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
