// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credit_cards.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const addDailyInterestToUnbilled = `-- name: AddDailyInterestToUnbilled :exec
UPDATE credit_cards
SET unbilled_balance = unbilled_balance + $2,
	updated_at = now()
WHERE debt_id = $1
`

type AddDailyInterestToUnbilledParams struct {
	DebtID          uuid.UUID
	UnbilledBalance decimal.Decimal
}

func (q *Queries) AddDailyInterestToUnbilled(ctx context.Context, arg AddDailyInterestToUnbilledParams) error {
	_, err := q.db.ExecContext(ctx, addDailyInterestToUnbilled, arg.DebtID, arg.UnbilledBalance)
	return err
}

const applyCreditCardPayment = `-- name: ApplyCreditCardPayment :exec
UPDATE credit_cards
SET billed_balance = GREATEST(0, billed_balance - $2),
	in_grace_period = CASE 
		WHEN (billed_balance - $2) <= 10 THEN TRUE 
		ELSE FALSE 
	END,
	updated_at = now()
WHERE debt_id = $1
`

type ApplyCreditCardPaymentParams struct {
	DebtID        uuid.UUID
	BilledBalance decimal.Decimal
}

func (q *Queries) ApplyCreditCardPayment(ctx context.Context, arg ApplyCreditCardPaymentParams) error {
	_, err := q.db.ExecContext(ctx, applyCreditCardPayment, arg.DebtID, arg.BilledBalance)
	return err
}

const createCreditCard = `-- name: CreateCreditCard :one
INSERT INTO credit_cards (
	debt_id, billing_day, grace_period_days, min_payment_percent,
	billed_balance, unbilled_balance, in_grace_period
) VALUES (
	$1, $2, $3, $4, $5, $6, $7
)
RETURNING debt_id, billing_day, grace_period_days, min_payment_percent, last_statement_date, payment_due_date, billed_balance, unbilled_balance, in_grace_period, created_at, updated_at
`

type CreateCreditCardParams struct {
	DebtID            uuid.UUID
	BillingDay        int32
	GracePeriodDays   int32
	MinPaymentPercent decimal.Decimal
	BilledBalance     decimal.Decimal
	UnbilledBalance   decimal.Decimal
	InGracePeriod     bool
}

func (q *Queries) CreateCreditCard(ctx context.Context, arg CreateCreditCardParams) (CreditCard, error) {
	row := q.db.QueryRowContext(ctx, createCreditCard,
		arg.DebtID,
		arg.BillingDay,
		arg.GracePeriodDays,
		arg.MinPaymentPercent,
		arg.BilledBalance,
		arg.UnbilledBalance,
		arg.InGracePeriod,
	)
	var i CreditCard
	err := row.Scan(
		&i.DebtID,
		&i.BillingDay,
		&i.GracePeriodDays,
		&i.MinPaymentPercent,
		&i.LastStatementDate,
		&i.PaymentDueDate,
		&i.BilledBalance,
		&i.UnbilledBalance,
		&i.InGracePeriod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const generateStatement = `-- name: GenerateStatement :exec
UPDATE credit_cards
SET billed_balance = unbilled_balance,
	unbilled_balance = 0,
	last_statement_date = $2,
	payment_due_date = $3,
	in_grace_period = TRUE,
	updated_at = now()
WHERE debt_id = $1
`

type GenerateStatementParams struct {
	DebtID            uuid.UUID
	LastStatementDate sql.NullTime
	PaymentDueDate    sql.NullTime
}

func (q *Queries) GenerateStatement(ctx context.Context, arg GenerateStatementParams) error {
	_, err := q.db.ExecContext(ctx, generateStatement, arg.DebtID, arg.LastStatementDate, arg.PaymentDueDate)
	return err
}

const getCreditCardByDebtID = `-- name: GetCreditCardByDebtID :one
SELECT debt_id, billing_day, grace_period_days, min_payment_percent, last_statement_date, payment_due_date, billed_balance, unbilled_balance, in_grace_period, created_at, updated_at FROM credit_cards
WHERE debt_id = $1
`

func (q *Queries) GetCreditCardByDebtID(ctx context.Context, debtID uuid.UUID) (CreditCard, error) {
	row := q.db.QueryRowContext(ctx, getCreditCardByDebtID, debtID)
	var i CreditCard
	err := row.Scan(
		&i.DebtID,
		&i.BillingDay,
		&i.GracePeriodDays,
		&i.MinPaymentPercent,
		&i.LastStatementDate,
		&i.PaymentDueDate,
		&i.BilledBalance,
		&i.UnbilledBalance,
		&i.InGracePeriod,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCreditCardsNeedingStatement = `-- name: ListCreditCardsNeedingStatement :many
SELECT cc.debt_id, cc.billing_day, cc.grace_period_days, cc.min_payment_percent, cc.last_statement_date, cc.payment_due_date, cc.billed_balance, cc.unbilled_balance, cc.in_grace_period, cc.created_at, cc.updated_at, d.user_id, d.name, d.outstanding_balance
FROM credit_cards cc
JOIN debts d ON cc.debt_id = d.id
WHERE EXTRACT(DAY FROM CURRENT_DATE) = cc.billing_day
	AND (cc.last_statement_date IS NULL OR cc.last_statement_date < CURRENT_DATE)
`

type ListCreditCardsNeedingStatementRow struct {
	DebtID             uuid.UUID
	BillingDay         int32
	GracePeriodDays    int32
	MinPaymentPercent  decimal.Decimal
	LastStatementDate  sql.NullTime
	PaymentDueDate     sql.NullTime
	BilledBalance      decimal.Decimal
	UnbilledBalance    decimal.Decimal
	InGracePeriod      bool
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	UserID             uuid.UUID
	Name               string
	OutstandingBalance decimal.Decimal
}

func (q *Queries) ListCreditCardsNeedingStatement(ctx context.Context) ([]ListCreditCardsNeedingStatementRow, error) {
	rows, err := q.db.QueryContext(ctx, listCreditCardsNeedingStatement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCreditCardsNeedingStatementRow
	for rows.Next() {
		var i ListCreditCardsNeedingStatementRow
		if err := rows.Scan(
			&i.DebtID,
			&i.BillingDay,
			&i.GracePeriodDays,
			&i.MinPaymentPercent,
			&i.LastStatementDate,
			&i.PaymentDueDate,
			&i.BilledBalance,
			&i.UnbilledBalance,
			&i.InGracePeriod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
			&i.OutstandingBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreditCardsOutOfGrace = `-- name: ListCreditCardsOutOfGrace :many
SELECT cc.debt_id, cc.billing_day, cc.grace_period_days, cc.min_payment_percent, cc.last_statement_date, cc.payment_due_date, cc.billed_balance, cc.unbilled_balance, cc.in_grace_period, cc.created_at, cc.updated_at, d.user_id, d.name, d.outstanding_balance, d.interest_rate, d.last_accrual_date
FROM credit_cards cc
JOIN debts d ON cc.debt_id = d.id
WHERE cc.in_grace_period = FALSE
	AND d.outstanding_balance > 0
`

type ListCreditCardsOutOfGraceRow struct {
	DebtID             uuid.UUID
	BillingDay         int32
	GracePeriodDays    int32
	MinPaymentPercent  decimal.Decimal
	LastStatementDate  sql.NullTime
	PaymentDueDate     sql.NullTime
	BilledBalance      decimal.Decimal
	UnbilledBalance    decimal.Decimal
	InGracePeriod      bool
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	UserID             uuid.UUID
	Name               string
	OutstandingBalance decimal.Decimal
	InterestRate       decimal.Decimal
	LastAccrualDate    time.Time
}

func (q *Queries) ListCreditCardsOutOfGrace(ctx context.Context) ([]ListCreditCardsOutOfGraceRow, error) {
	rows, err := q.db.QueryContext(ctx, listCreditCardsOutOfGrace)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCreditCardsOutOfGraceRow
	for rows.Next() {
		var i ListCreditCardsOutOfGraceRow
		if err := rows.Scan(
			&i.DebtID,
			&i.BillingDay,
			&i.GracePeriodDays,
			&i.MinPaymentPercent,
			&i.LastStatementDate,
			&i.PaymentDueDate,
			&i.BilledBalance,
			&i.UnbilledBalance,
			&i.InGracePeriod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.Name,
			&i.OutstandingBalance,
			&i.InterestRate,
			&i.LastAccrualDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCreditCardBalances = `-- name: UpdateCreditCardBalances :exec
UPDATE credit_cards
SET billed_balance = $2,
	unbilled_balance = $3,
	in_grace_period = $4,
	updated_at = now()
WHERE debt_id = $1
`

type UpdateCreditCardBalancesParams struct {
	DebtID          uuid.UUID
	BilledBalance   decimal.Decimal
	UnbilledBalance decimal.Decimal
	InGracePeriod   bool
}

func (q *Queries) UpdateCreditCardBalances(ctx context.Context, arg UpdateCreditCardBalancesParams) error {
	_, err := q.db.ExecContext(ctx, updateCreditCardBalances,
		arg.DebtID,
		arg.BilledBalance,
		arg.UnbilledBalance,
		arg.InGracePeriod,
	)
	return err
}
