// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: debts.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const accrueInterest = `-- name: AccrueInterest :exec
UPDATE debts
SET accrued_interest = accrued_interest + $2,
    last_accrual_date = $3,
    updated_at = now()
WHERE id = $1
`

type AccrueInterestParams struct {
	ID              uuid.UUID
	AccruedInterest decimal.Decimal
	LastAccrualDate time.Time
}

func (q *Queries) AccrueInterest(ctx context.Context, arg AccrueInterestParams) error {
	_, err := q.db.ExecContext(ctx, accrueInterest, arg.ID, arg.AccruedInterest, arg.LastAccrualDate)
	return err
}

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (
  user_id, name, type, lender, principal_decimal,
  outstanding_balance, interest_rate, min_payment,
  due_date, payment_frequency, debt_taken,
  risk_level, priority, notes,
  payment_due_day, emi_amount, tenure_months, months_paid, moratorium_until, in_moratorium
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14,
  $15, $16, $17, $18, $19, $20
)
RETURNING id, user_id, name, type, lender, principal_decimal, outstanding_balance, interest_rate, min_payment, due_date, payment_frequency, is_overdue, late_fees, other_charges, debt_taken, risk_level, debt_health_score, priority, notes, created_at, updated_at, accrued_interest, last_accrual_date, payment_due_day, emi_amount, tenure_months, months_paid, moratorium_until, in_moratorium
`

type CreateDebtParams struct {
	UserID             uuid.UUID
	Name               string
	Type               DebtType
	Lender             sql.NullString
	PrincipalDecimal   decimal.Decimal
	OutstandingBalance decimal.Decimal
	InterestRate       decimal.Decimal
	MinPayment         decimal.Decimal
	DueDate            time.Time
	PaymentFrequency   NullPaymentFreq
	DebtTaken          sql.NullTime
	RiskLevel          NullRiskLevel
	Priority           sql.NullInt16
	Notes              sql.NullString
	PaymentDueDay      sql.NullInt32
	EmiAmount          sql.NullString
	TenureMonths       sql.NullInt32
	MonthsPaid         sql.NullInt32
	MoratoriumUntil    sql.NullTime
	InMoratorium       sql.NullBool
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRowContext(ctx, createDebt,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Lender,
		arg.PrincipalDecimal,
		arg.OutstandingBalance,
		arg.InterestRate,
		arg.MinPayment,
		arg.DueDate,
		arg.PaymentFrequency,
		arg.DebtTaken,
		arg.RiskLevel,
		arg.Priority,
		arg.Notes,
		arg.PaymentDueDay,
		arg.EmiAmount,
		arg.TenureMonths,
		arg.MonthsPaid,
		arg.MoratoriumUntil,
		arg.InMoratorium,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Lender,
		&i.PrincipalDecimal,
		&i.OutstandingBalance,
		&i.InterestRate,
		&i.MinPayment,
		&i.DueDate,
		&i.PaymentFrequency,
		&i.IsOverdue,
		&i.LateFees,
		&i.OtherCharges,
		&i.DebtTaken,
		&i.RiskLevel,
		&i.DebtHealthScore,
		&i.Priority,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccruedInterest,
		&i.LastAccrualDate,
		&i.PaymentDueDay,
		&i.EmiAmount,
		&i.TenureMonths,
		&i.MonthsPaid,
		&i.MoratoriumUntil,
		&i.InMoratorium,
	)
	return i, err
}

const exitMoratorium = `-- name: ExitMoratorium :exec
UPDATE debts
SET in_moratorium = FALSE,
	emi_amount = $2,
	updated_at = now()
WHERE id = $1
`

type ExitMoratoriumParams struct {
	ID        uuid.UUID
	EmiAmount sql.NullString
}

func (q *Queries) ExitMoratorium(ctx context.Context, arg ExitMoratoriumParams) error {
	_, err := q.db.ExecContext(ctx, exitMoratorium, arg.ID, arg.EmiAmount)
	return err
}

const getDebtBreakdownByType = `-- name: GetDebtBreakdownByType :many
SELECT 
    type,
    COUNT(*) as count,
    COALESCE(SUM(outstanding_balance + accrued_interest), 0) as total_outstanding,
    COALESCE(SUM(min_payment), 0) as total_min_payment,
    CASE 
        WHEN SUM(outstanding_balance) > 0 
        THEN ROUND((SUM(interest_rate * outstanding_balance) / SUM(outstanding_balance))::numeric, 5)
        ELSE 0
    END as avg_interest_rate
FROM debts
WHERE user_id = $1 
    AND outstanding_balance > 0
GROUP BY type
ORDER BY total_outstanding DESC
`

type GetDebtBreakdownByTypeRow struct {
	Type             DebtType
	Count            int64
	TotalOutstanding interface{}
	TotalMinPayment  interface{}
	AvgInterestRate  int32
}

// Breakdown of debts by type for visualization
func (q *Queries) GetDebtBreakdownByType(ctx context.Context, userID uuid.UUID) ([]GetDebtBreakdownByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, getDebtBreakdownByType, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDebtBreakdownByTypeRow
	for rows.Next() {
		var i GetDebtBreakdownByTypeRow
		if err := rows.Scan(
			&i.Type,
			&i.Count,
			&i.TotalOutstanding,
			&i.TotalMinPayment,
			&i.AvgInterestRate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDebtByID = `-- name: GetDebtByID :one
SELECT id, user_id, name, type, lender, principal_decimal, outstanding_balance, interest_rate, min_payment, due_date, payment_frequency, is_overdue, late_fees, other_charges, debt_taken, risk_level, debt_health_score, priority, notes, created_at, updated_at, accrued_interest, last_accrual_date, payment_due_day, emi_amount, tenure_months, months_paid, moratorium_until, in_moratorium
FROM debts
WHERE id = $1 AND user_id = $2
`

type GetDebtByIDParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDebtByID(ctx context.Context, arg GetDebtByIDParams) (Debt, error) {
	row := q.db.QueryRowContext(ctx, getDebtByID, arg.ID, arg.UserID)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Lender,
		&i.PrincipalDecimal,
		&i.OutstandingBalance,
		&i.InterestRate,
		&i.MinPayment,
		&i.DueDate,
		&i.PaymentFrequency,
		&i.IsOverdue,
		&i.LateFees,
		&i.OtherCharges,
		&i.DebtTaken,
		&i.RiskLevel,
		&i.DebtHealthScore,
		&i.Priority,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccruedInterest,
		&i.LastAccrualDate,
		&i.PaymentDueDay,
		&i.EmiAmount,
		&i.TenureMonths,
		&i.MonthsPaid,
		&i.MoratoriumUntil,
		&i.InMoratorium,
	)
	return i, err
}

const getDebtForUpdate = `-- name: GetDebtForUpdate :one
SELECT id, user_id, name, type, lender, principal_decimal, outstanding_balance, interest_rate, min_payment, due_date, payment_frequency, is_overdue, late_fees, other_charges, debt_taken, risk_level, debt_health_score, priority, notes, created_at, updated_at, accrued_interest, last_accrual_date, payment_due_day, emi_amount, tenure_months, months_paid, moratorium_until, in_moratorium
FROM debts
WHERE id = $1 AND user_id = $2
FOR UPDATE
`

type GetDebtForUpdateParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetDebtForUpdate(ctx context.Context, arg GetDebtForUpdateParams) (Debt, error) {
	row := q.db.QueryRowContext(ctx, getDebtForUpdate, arg.ID, arg.UserID)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Lender,
		&i.PrincipalDecimal,
		&i.OutstandingBalance,
		&i.InterestRate,
		&i.MinPayment,
		&i.DueDate,
		&i.PaymentFrequency,
		&i.IsOverdue,
		&i.LateFees,
		&i.OtherCharges,
		&i.DebtTaken,
		&i.RiskLevel,
		&i.DebtHealthScore,
		&i.Priority,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.AccruedInterest,
		&i.LastAccrualDate,
		&i.PaymentDueDay,
		&i.EmiAmount,
		&i.TenureMonths,
		&i.MonthsPaid,
		&i.MoratoriumUntil,
		&i.InMoratorium,
	)
	return i, err
}

const getDebtsByRiskLevel = `-- name: GetDebtsByRiskLevel :many
SELECT 
    risk_level,
    COUNT(*) as count,
    COALESCE(SUM(outstanding_balance + accrued_interest), 0) as total_outstanding,
    COALESCE(AVG(debt_health_score), 0) as avg_health_score
FROM debts
WHERE user_id = $1 
    AND outstanding_balance > 0
    AND risk_level IS NOT NULL
GROUP BY risk_level
ORDER BY 
    CASE risk_level
        WHEN 'high' THEN 1
        WHEN 'medium' THEN 2
        WHEN 'low' THEN 3
    END
`

type GetDebtsByRiskLevelRow struct {
	RiskLevel        NullRiskLevel
	Count            int64
	TotalOutstanding interface{}
	AvgHealthScore   interface{}
}

// Group debts by risk level
func (q *Queries) GetDebtsByRiskLevel(ctx context.Context, userID uuid.UUID) ([]GetDebtsByRiskLevelRow, error) {
	rows, err := q.db.QueryContext(ctx, getDebtsByRiskLevel, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDebtsByRiskLevelRow
	for rows.Next() {
		var i GetDebtsByRiskLevelRow
		if err := rows.Scan(
			&i.RiskLevel,
			&i.Count,
			&i.TotalOutstanding,
			&i.AvgHealthScore,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllActiveDebts = `-- name: ListAllActiveDebts :many
SELECT id, user_id, name, type, lender, principal_decimal, outstanding_balance, interest_rate, min_payment, due_date, payment_frequency, is_overdue, late_fees, other_charges, debt_taken, risk_level, debt_health_score, priority, notes, created_at, updated_at, accrued_interest, last_accrual_date, payment_due_day, emi_amount, tenure_months, months_paid, moratorium_until, in_moratorium
FROM debts
WHERE outstanding_balance > 0 OR accrued_interest > 0
`

func (q *Queries) ListAllActiveDebts(ctx context.Context) ([]Debt, error) {
	rows, err := q.db.QueryContext(ctx, listAllActiveDebts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debt
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Lender,
			&i.PrincipalDecimal,
			&i.OutstandingBalance,
			&i.InterestRate,
			&i.MinPayment,
			&i.DueDate,
			&i.PaymentFrequency,
			&i.IsOverdue,
			&i.LateFees,
			&i.OtherCharges,
			&i.DebtTaken,
			&i.RiskLevel,
			&i.DebtHealthScore,
			&i.Priority,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccruedInterest,
			&i.LastAccrualDate,
			&i.PaymentDueDay,
			&i.EmiAmount,
			&i.TenureMonths,
			&i.MonthsPaid,
			&i.MoratoriumUntil,
			&i.InMoratorium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLoansNeedingEMI = `-- name: ListLoansNeedingEMI :many
SELECT id, user_id, name, type, lender, principal_decimal, outstanding_balance, interest_rate, min_payment, due_date, payment_frequency, is_overdue, late_fees, other_charges, debt_taken, risk_level, debt_health_score, priority, notes, created_at, updated_at, accrued_interest, last_accrual_date, payment_due_day, emi_amount, tenure_months, months_paid, moratorium_until, in_moratorium
FROM debts
WHERE type IN ('personal_loan', 'student_loan', 'mortgage')
	AND payment_due_day IS NOT NULL
	AND outstanding_balance > 0
	AND EXTRACT(DAY FROM CURRENT_DATE) = payment_due_day
`

func (q *Queries) ListLoansNeedingEMI(ctx context.Context) ([]Debt, error) {
	rows, err := q.db.QueryContext(ctx, listLoansNeedingEMI)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debt
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Lender,
			&i.PrincipalDecimal,
			&i.OutstandingBalance,
			&i.InterestRate,
			&i.MinPayment,
			&i.DueDate,
			&i.PaymentFrequency,
			&i.IsOverdue,
			&i.LateFees,
			&i.OtherCharges,
			&i.DebtTaken,
			&i.RiskLevel,
			&i.DebtHealthScore,
			&i.Priority,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccruedInterest,
			&i.LastAccrualDate,
			&i.PaymentDueDay,
			&i.EmiAmount,
			&i.TenureMonths,
			&i.MonthsPaid,
			&i.MoratoriumUntil,
			&i.InMoratorium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDebts = `-- name: ListUserDebts :many
SELECT id, user_id, name, type, lender, principal_decimal, outstanding_balance, interest_rate, min_payment, due_date, payment_frequency, is_overdue, late_fees, other_charges, debt_taken, risk_level, debt_health_score, priority, notes, created_at, updated_at, accrued_interest, last_accrual_date, payment_due_day, emi_amount, tenure_months, months_paid, moratorium_until, in_moratorium
FROM debts
WHERE user_id = $1
ORDER BY priority DESC, due_date ASC
`

func (q *Queries) ListUserDebts(ctx context.Context, userID uuid.UUID) ([]Debt, error) {
	rows, err := q.db.QueryContext(ctx, listUserDebts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debt
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Lender,
			&i.PrincipalDecimal,
			&i.OutstandingBalance,
			&i.InterestRate,
			&i.MinPayment,
			&i.DueDate,
			&i.PaymentFrequency,
			&i.IsOverdue,
			&i.LateFees,
			&i.OtherCharges,
			&i.DebtTaken,
			&i.RiskLevel,
			&i.DebtHealthScore,
			&i.Priority,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.AccruedInterest,
			&i.LastAccrualDate,
			&i.PaymentDueDay,
			&i.EmiAmount,
			&i.TenureMonths,
			&i.MonthsPaid,
			&i.MoratoriumUntil,
			&i.InMoratorium,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDebtOverdue = `-- name: MarkDebtOverdue :exec
UPDATE debts
SET is_overdue = TRUE, updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkDebtOverdue(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markDebtOverdue, id)
	return err
}

const resetAccruedInterest = `-- name: ResetAccruedInterest :exec
UPDATE debts
SET accrued_interest = 0,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) ResetAccruedInterest(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, resetAccruedInterest, id)
	return err
}

const updateDebtAfterPayment = `-- name: UpdateDebtAfterPayment :exec
UPDATE debts
SET outstanding_balance = $2,
    accrued_interest = $3,
    last_accrual_date = $4,
    updated_at = now()
WHERE id = $1
`

type UpdateDebtAfterPaymentParams struct {
	ID                 uuid.UUID
	OutstandingBalance decimal.Decimal
	AccruedInterest    decimal.Decimal
	LastAccrualDate    time.Time
}

func (q *Queries) UpdateDebtAfterPayment(ctx context.Context, arg UpdateDebtAfterPaymentParams) error {
	_, err := q.db.ExecContext(ctx, updateDebtAfterPayment,
		arg.ID,
		arg.OutstandingBalance,
		arg.AccruedInterest,
		arg.LastAccrualDate,
	)
	return err
}

const updateDebtBalance = `-- name: UpdateDebtBalance :exec
UPDATE debts
SET outstanding_balance = $2,
    is_overdue = $3,
    updated_at = now()
WHERE id = $1
`

type UpdateDebtBalanceParams struct {
	ID                 uuid.UUID
	OutstandingBalance decimal.Decimal
	IsOverdue          sql.NullBool
}

func (q *Queries) UpdateDebtBalance(ctx context.Context, arg UpdateDebtBalanceParams) error {
	_, err := q.db.ExecContext(ctx, updateDebtBalance, arg.ID, arg.OutstandingBalance, arg.IsOverdue)
	return err
}

const updateDebtHealthScore = `-- name: UpdateDebtHealthScore :exec
UPDATE debts
SET debt_health_score = $2, updated_at = now()
WHERE id = $1
`

type UpdateDebtHealthScoreParams struct {
	ID              uuid.UUID
	DebtHealthScore sql.NullString
}

func (q *Queries) UpdateDebtHealthScore(ctx context.Context, arg UpdateDebtHealthScoreParams) error {
	_, err := q.db.ExecContext(ctx, updateDebtHealthScore, arg.ID, arg.DebtHealthScore)
	return err
}

const updateLoanPayment = `-- name: UpdateLoanPayment :exec
UPDATE debts
SET months_paid = months_paid + 1,
	updated_at = now()
WHERE id = $1
`

func (q *Queries) UpdateLoanPayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, updateLoanPayment, id)
	return err
}
