// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: finance_steps.sql

package database

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// FinanceStep is the row type for finance_steps table (used by finance_steps queries).
type FinanceStep struct {
	SessionID         uuid.UUID
	MonthlyIncome    decimal.NullDecimal
	FixedObligations decimal.NullDecimal
	Loans             json.RawMessage
	EngineVersion    sql.NullString
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

const upsertFinanceSteps = `-- name: UpsertFinanceSteps :one
INSERT INTO finance_steps (session_id, monthly_income, fixed_obligations, loans, engine_version, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, now(), now())
ON CONFLICT (session_id) DO UPDATE SET
    monthly_income = EXCLUDED.monthly_income,
    fixed_obligations = EXCLUDED.fixed_obligations,
    loans = EXCLUDED.loans,
    engine_version = EXCLUDED.engine_version,
    updated_at = now()
RETURNING session_id, monthly_income, fixed_obligations, loans, engine_version, created_at, updated_at
`

type UpsertFinanceStepsParams struct {
	SessionID         uuid.UUID
	MonthlyIncome    decimal.NullDecimal
	FixedObligations decimal.NullDecimal
	Loans             json.RawMessage
	EngineVersion    sql.NullString
}

func (q *Queries) UpsertFinanceSteps(ctx context.Context, arg UpsertFinanceStepsParams) (FinanceStep, error) {
	row := q.db.QueryRowContext(ctx, upsertFinanceSteps,
		arg.SessionID,
		arg.MonthlyIncome,
		arg.FixedObligations,
		arg.Loans,
		arg.EngineVersion,
	)
	var i FinanceStep
	err := row.Scan(
		&i.SessionID,
		&i.MonthlyIncome,
		&i.FixedObligations,
		&i.Loans,
		&i.EngineVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFinanceStepsBySessionID = `-- name: GetFinanceStepsBySessionID :one
SELECT session_id, monthly_income, fixed_obligations, loans, engine_version, created_at, updated_at FROM finance_steps WHERE session_id = $1
`

func (q *Queries) GetFinanceStepsBySessionID(ctx context.Context, sessionID uuid.UUID) (FinanceStep, error) {
	row := q.db.QueryRowContext(ctx, getFinanceStepsBySessionID, sessionID)
	var i FinanceStep
	err := row.Scan(
		&i.SessionID,
		&i.MonthlyIncome,
		&i.FixedObligations,
		&i.Loans,
		&i.EngineVersion,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteFinanceStepsBySessionID = `-- name: DeleteFinanceStepsBySessionID :exec
DELETE FROM finance_steps WHERE session_id = $1
`

func (q *Queries) DeleteFinanceStepsBySessionID(ctx context.Context, sessionID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteFinanceStepsBySessionID, sessionID)
	return err
}
