// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: lead_email.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const checkEmailExists = `-- name: CheckEmailExists :one
SELECT EXISTS(SELECT 1 FROM lead_emails WHERE email = $1) AS exists
`

func (q *Queries) CheckEmailExists(ctx context.Context, email string) (bool, error) {
	row := q.db.QueryRowContext(ctx, checkEmailExists, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countLeadEmailsBySource = `-- name: CountLeadEmailsBySource :one
SELECT 
    COUNT(*) FILTER (WHERE source = 'waitlist')::int AS waitlist_count,
    COUNT(*) FILTER (WHERE source = 'pdf')::int AS pdf_count,
    COUNT(*)::int AS total_count
FROM lead_emails
`

type CountLeadEmailsBySourceRow struct {
	WaitlistCount int32
	PdfCount      int32
	TotalCount    int32
}

func (q *Queries) CountLeadEmailsBySource(ctx context.Context) (CountLeadEmailsBySourceRow, error) {
	row := q.db.QueryRowContext(ctx, countLeadEmailsBySource)
	var i CountLeadEmailsBySourceRow
	err := row.Scan(&i.WaitlistCount, &i.PdfCount, &i.TotalCount)
	return i, err
}

const createLeadEmail = `-- name: CreateLeadEmail :one
INSERT INTO lead_emails (email, source, session_id)
VALUES ($1, $2, $3)
RETURNING id, email, source, session_id, created_at
`

type CreateLeadEmailParams struct {
	Email     string
	Source    string
	SessionID uuid.NullUUID
}

func (q *Queries) CreateLeadEmail(ctx context.Context, arg CreateLeadEmailParams) (LeadEmail, error) {
	row := q.db.QueryRowContext(ctx, createLeadEmail, arg.Email, arg.Source, arg.SessionID)
	var i LeadEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Source,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getLeadEmailByEmail = `-- name: GetLeadEmailByEmail :one
SELECT id, email, source, session_id, created_at FROM lead_emails WHERE email = $1 LIMIT 1
`

func (q *Queries) GetLeadEmailByEmail(ctx context.Context, email string) (LeadEmail, error) {
	row := q.db.QueryRowContext(ctx, getLeadEmailByEmail, email)
	var i LeadEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Source,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const getLeadEmailByID = `-- name: GetLeadEmailByID :one
SELECT id, email, source, session_id, created_at FROM lead_emails WHERE id = $1
`

func (q *Queries) GetLeadEmailByID(ctx context.Context, id uuid.UUID) (LeadEmail, error) {
	row := q.db.QueryRowContext(ctx, getLeadEmailByID, id)
	var i LeadEmail
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Source,
		&i.SessionID,
		&i.CreatedAt,
	)
	return i, err
}

const listLeadEmails = `-- name: ListLeadEmails :many
SELECT id, email, source, session_id, created_at FROM lead_emails
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListLeadEmailsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListLeadEmails(ctx context.Context, arg ListLeadEmailsParams) ([]LeadEmail, error) {
	rows, err := q.db.QueryContext(ctx, listLeadEmails, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeadEmail
	for rows.Next() {
		var i LeadEmail
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Source,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadEmailsBySource = `-- name: ListLeadEmailsBySource :many
SELECT id, email, source, session_id, created_at FROM lead_emails
WHERE source = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListLeadEmailsBySourceParams struct {
	Source string
	Limit  int32
	Offset int32
}

func (q *Queries) ListLeadEmailsBySource(ctx context.Context, arg ListLeadEmailsBySourceParams) ([]LeadEmail, error) {
	rows, err := q.db.QueryContext(ctx, listLeadEmailsBySource, arg.Source, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LeadEmail
	for rows.Next() {
		var i LeadEmail
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Source,
			&i.SessionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
