// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
	"github.com/sqlc-dev/pqtype"
)

type DebtType string

const (
	DebtTypeCreditCard   DebtType = "credit_card"
	DebtTypePersonalLoan DebtType = "personal_loan"
	DebtTypeStudentLoan  DebtType = "student_loan"
	DebtTypeMortgage     DebtType = "mortgage"
	DebtTypeMedical      DebtType = "medical"
	DebtTypeOther        DebtType = "other"
)

func (e *DebtType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DebtType(s)
	case string:
		*e = DebtType(s)
	default:
		return fmt.Errorf("unsupported scan type for DebtType: %T", src)
	}
	return nil
}

type NullDebtType struct {
	DebtType DebtType
	Valid    bool // Valid is true if DebtType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDebtType) Scan(value interface{}) error {
	if value == nil {
		ns.DebtType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DebtType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDebtType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DebtType), nil
}

type PaymentFreq string

const (
	PaymentFreqMonthly  PaymentFreq = "monthly"
	PaymentFreqBiweekly PaymentFreq = "biweekly"
	PaymentFreqWeekly   PaymentFreq = "weekly"
)

func (e *PaymentFreq) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentFreq(s)
	case string:
		*e = PaymentFreq(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentFreq: %T", src)
	}
	return nil
}

type NullPaymentFreq struct {
	PaymentFreq PaymentFreq
	Valid       bool // Valid is true if PaymentFreq is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentFreq) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentFreq, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentFreq.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentFreq) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentFreq), nil
}

type PaymentType string

const (
	PaymentTypeMinimum PaymentType = "minimum"
	PaymentTypeExtra   PaymentType = "extra"
	PaymentTypeFull    PaymentType = "full"
	PaymentTypeLate    PaymentType = "late"
)

func (e *PaymentType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentType(s)
	case string:
		*e = PaymentType(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentType: %T", src)
	}
	return nil
}

type NullPaymentType struct {
	PaymentType PaymentType
	Valid       bool // Valid is true if PaymentType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentType) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentType), nil
}

type RiskLevel string

const (
	RiskLevelLow    RiskLevel = "low"
	RiskLevelMedium RiskLevel = "medium"
	RiskLevelHigh   RiskLevel = "high"
)

func (e *RiskLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RiskLevel(s)
	case string:
		*e = RiskLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for RiskLevel: %T", src)
	}
	return nil
}

type NullRiskLevel struct {
	RiskLevel RiskLevel
	Valid     bool // Valid is true if RiskLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRiskLevel) Scan(value interface{}) error {
	if value == nil {
		ns.RiskLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RiskLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRiskLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RiskLevel), nil
}

type CalculationEvent struct {
	ID        uuid.UUID
	SessionID uuid.UUID
	EventType string
	Metadata  json.RawMessage
	CreatedAt time.Time
}

type CalculationSession struct {
	ID            uuid.UUID
	SessionID     uuid.UUID
	EngineVersion string
	CreatedAt     time.Time
}

type CalculationSessionMetric struct {
	SessionID          uuid.UUID
	EngineVersion      string
	CalculationRuns    int32
	StrategySwitches   int32
	InputModifications int32
	PdfRequested       bool
	EmailSubmitted     bool
	FirstSeenAt        time.Time
	LastSeenAt         time.Time
}

type CreditCard struct {
	DebtID            uuid.UUID
	BillingDay        int32
	GracePeriodDays   int32
	MinPaymentPercent decimal.Decimal
	LastStatementDate sql.NullTime
	PaymentDueDate    sql.NullTime
	BilledBalance     decimal.Decimal
	UnbilledBalance   decimal.Decimal
	InGracePeriod     bool
	CreatedAt         sql.NullTime
	UpdatedAt         sql.NullTime
}

type Debt struct {
	ID                 uuid.UUID
	UserID             uuid.UUID
	Name               string
	Type               DebtType
	Lender             sql.NullString
	PrincipalDecimal   decimal.Decimal
	OutstandingBalance decimal.Decimal
	InterestRate       decimal.Decimal
	MinPayment         decimal.Decimal
	DueDate            time.Time
	PaymentFrequency   NullPaymentFreq
	IsOverdue          sql.NullBool
	LateFees           sql.NullString
	OtherCharges       sql.NullString
	DebtTaken          sql.NullTime
	RiskLevel          NullRiskLevel
	DebtHealthScore    sql.NullString
	Priority           sql.NullInt16
	Notes              sql.NullString
	CreatedAt          sql.NullTime
	UpdatedAt          sql.NullTime
	AccruedInterest    decimal.Decimal
	LastAccrualDate    time.Time
	PaymentDueDay      sql.NullInt32
	EmiAmount          sql.NullString
	TenureMonths       sql.NullInt32
	MonthsPaid         sql.NullInt32
	MoratoriumUntil    sql.NullTime
	InMoratorium       sql.NullBool
}

type LeadEmail struct {
	ID        uuid.UUID
	Email     string
	Source    string
	SessionID uuid.NullUUID
	CreatedAt time.Time
}

type NotificationEvent struct {
	ID           uuid.UUID
	UserID       uuid.UUID
	EventType    string
	Channel      string
	Recipient    string
	Status       string
	ErrorMessage sql.NullString
	Metadata     pqtype.NullRawMessage
	SentAt       sql.NullTime
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type PaymentsHistory struct {
	ID               uuid.UUID
	DebtID           uuid.UUID
	Amount           decimal.Decimal
	PaymentDate      time.Time
	Type             PaymentType
	Notes            sql.NullString
	PrincipalApplied decimal.Decimal
	InterestApplied  decimal.Decimal
	PaymentMethod    sql.NullString
	CreatedAt        sql.NullTime
}

type RefreshToken struct {
	Token     string
	UserID    uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	ExpiresAt time.Time
	RevokedAt sql.NullTime
}

type User struct {
	ID            uuid.UUID
	Name          string
	Email         string
	PasswordHash  string
	MonthlyIncome decimal.Decimal
	IsActive      sql.NullBool
	CreatedAt     time.Time
	UpdatedAt     time.Time
}
