// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notifications.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
	"github.com/sqlc-dev/pqtype"
)

const createNotificationEvent = `-- name: CreateNotificationEvent :one
INSERT INTO notification_events (user_id, event_type, channel, recipient, status, metadata)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, event_type, channel, recipient, status, error_message, metadata, sent_at, created_at, updated_at
`

type CreateNotificationEventParams struct {
	UserID    uuid.UUID
	EventType string
	Channel   string
	Recipient string
	Status    string
	Metadata  pqtype.NullRawMessage
}

func (q *Queries) CreateNotificationEvent(ctx context.Context, arg CreateNotificationEventParams) (NotificationEvent, error) {
	row := q.db.QueryRowContext(ctx, createNotificationEvent,
		arg.UserID,
		arg.EventType,
		arg.Channel,
		arg.Recipient,
		arg.Status,
		arg.Metadata,
	)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.Channel,
		&i.Recipient,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotificationEventByID = `-- name: GetNotificationEventByID :one
SELECT id, user_id, event_type, channel, recipient, status, error_message, metadata, sent_at, created_at, updated_at
FROM notification_events
WHERE id = $1
`

func (q *Queries) GetNotificationEventByID(ctx context.Context, id uuid.UUID) (NotificationEvent, error) {
	row := q.db.QueryRowContext(ctx, getNotificationEventByID, id)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.Channel,
		&i.Recipient,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listNotificationEventsByUser = `-- name: ListNotificationEventsByUser :many
SELECT id, user_id, event_type, channel, recipient, status, error_message, metadata, sent_at, created_at, updated_at
FROM notification_events
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListNotificationEventsByUserParams struct {
	UserID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListNotificationEventsByUser(ctx context.Context, arg ListNotificationEventsByUserParams) ([]NotificationEvent, error) {
	rows, err := q.db.QueryContext(ctx, listNotificationEventsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotificationEvent
	for rows.Next() {
		var i NotificationEvent
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.EventType,
			&i.Channel,
			&i.Recipient,
			&i.Status,
			&i.ErrorMessage,
			&i.Metadata,
			&i.SentAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNotificationEventStatus = `-- name: UpdateNotificationEventStatus :one
UPDATE notification_events
SET status = $2,
    error_message = $3,
    sent_at = CASE WHEN $2::varchar = 'sent' THEN now() ELSE sent_at END,
    updated_at = now()
WHERE id = $1
RETURNING id, user_id, event_type, channel, recipient, status, error_message, metadata, sent_at, created_at, updated_at
`

type UpdateNotificationEventStatusParams struct {
	ID           uuid.UUID
	Status       string
	ErrorMessage sql.NullString
}

func (q *Queries) UpdateNotificationEventStatus(ctx context.Context, arg UpdateNotificationEventStatusParams) (NotificationEvent, error) {
	row := q.db.QueryRowContext(ctx, updateNotificationEventStatus, arg.ID, arg.Status, arg.ErrorMessage)
	var i NotificationEvent
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.EventType,
		&i.Channel,
		&i.Recipient,
		&i.Status,
		&i.ErrorMessage,
		&i.Metadata,
		&i.SentAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
