// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package database

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, debt_id, amount, payment_date, type, notes, principal_applied, interest_applied, payment_method, created_at
FROM payments_history
WHERE id = $1 AND debt_id = $2
`

type GetPaymentByIDParams struct {
	ID     uuid.UUID
	DebtID uuid.UUID
}

func (q *Queries) GetPaymentByID(ctx context.Context, arg GetPaymentByIDParams) (PaymentsHistory, error) {
	row := q.db.QueryRowContext(ctx, getPaymentByID, arg.ID, arg.DebtID)
	var i PaymentsHistory
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.Amount,
		&i.PaymentDate,
		&i.Type,
		&i.Notes,
		&i.PrincipalApplied,
		&i.InterestApplied,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentHistorySummary = `-- name: GetPaymentHistorySummary :one
SELECT 
    COALESCE(SUM(CASE WHEN p.payment_date >= CURRENT_DATE - INTERVAL '30 days' THEN p.amount ELSE 0 END), 0) as paid_last_30_days,
    COALESCE(SUM(CASE WHEN p.payment_date >= CURRENT_DATE - INTERVAL '90 days' THEN p.amount ELSE 0 END), 0) as paid_last_90_days,
    COALESCE(SUM(CASE WHEN p.payment_date >= CURRENT_DATE - INTERVAL '365 days' THEN p.amount ELSE 0 END), 0) as paid_last_year,
    COUNT(CASE WHEN p.payment_date >= CURRENT_DATE - INTERVAL '30 days' THEN 1 END) as payments_last_30_days
FROM payments_history p
JOIN debts d ON p.debt_id = d.id
WHERE d.user_id = $1
`

type GetPaymentHistorySummaryRow struct {
	PaidLast30Days     interface{}
	PaidLast90Days     interface{}
	PaidLastYear       interface{}
	PaymentsLast30Days int64
}

// Payment statistics for the last 30, 90, 365 days
func (q *Queries) GetPaymentHistorySummary(ctx context.Context, userID uuid.UUID) (GetPaymentHistorySummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getPaymentHistorySummary, userID)
	var i GetPaymentHistorySummaryRow
	err := row.Scan(
		&i.PaidLast30Days,
		&i.PaidLast90Days,
		&i.PaidLastYear,
		&i.PaymentsLast30Days,
	)
	return i, err
}

const getRecentPayments = `-- name: GetRecentPayments :many
SELECT p.id, p.debt_id, p.amount, p.payment_date, p.type, p.notes, p.principal_applied, p.interest_applied, p.payment_method, p.created_at, d.name AS debt_name
FROM payments_history p
JOIN debts d ON p.debt_id = d.id
WHERE p.payment_date >= $1
  AND d.user_id = $2
ORDER BY p.payment_date DESC
`

type GetRecentPaymentsParams struct {
	PaymentDate time.Time
	UserID      uuid.UUID
}

type GetRecentPaymentsRow struct {
	ID               uuid.UUID
	DebtID           uuid.UUID
	Amount           decimal.Decimal
	PaymentDate      time.Time
	Type             PaymentType
	Notes            sql.NullString
	PrincipalApplied decimal.Decimal
	InterestApplied  decimal.Decimal
	PaymentMethod    sql.NullString
	CreatedAt        sql.NullTime
	DebtName         string
}

func (q *Queries) GetRecentPayments(ctx context.Context, arg GetRecentPaymentsParams) ([]GetRecentPaymentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentPayments, arg.PaymentDate, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentPaymentsRow
	for rows.Next() {
		var i GetRecentPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DebtID,
			&i.Amount,
			&i.PaymentDate,
			&i.Type,
			&i.Notes,
			&i.PrincipalApplied,
			&i.InterestApplied,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.DebtName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingEMIs = `-- name: GetUpcomingEMIs :many
SELECT 
    id,
    name,
    type,
    lender,
    outstanding_balance,
    accrued_interest,
    COALESCE(emi_amount, min_payment) as payment_amount,
    due_date,
    payment_due_day,
    is_overdue,
    late_fees,
    CASE 
        WHEN is_overdue THEN 0
        WHEN due_date <= CURRENT_DATE THEN 0
        ELSE (due_date - CURRENT_DATE)
    END as days_until_due
FROM debts
WHERE user_id = $1 
    AND outstanding_balance > 0
    AND (
        (due_date BETWEEN CURRENT_DATE AND CURRENT_DATE + INTERVAL '30 days')
        OR is_overdue = TRUE
    )
ORDER BY 
    is_overdue DESC,
    due_date ASC
`

type GetUpcomingEMIsRow struct {
	ID                 uuid.UUID
	Name               string
	Type               DebtType
	Lender             sql.NullString
	OutstandingBalance decimal.Decimal
	AccruedInterest    decimal.Decimal
	PaymentAmount      decimal.Decimal
	DueDate            time.Time
	PaymentDueDay      sql.NullInt32
	IsOverdue          sql.NullBool
	LateFees           sql.NullString
	DaysUntilDue       interface{}
}

// Returns upcoming EMI/payments within the next 30 days
func (q *Queries) GetUpcomingEMIs(ctx context.Context, userID uuid.UUID) ([]GetUpcomingEMIsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingEMIs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUpcomingEMIsRow
	for rows.Next() {
		var i GetUpcomingEMIsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Lender,
			&i.OutstandingBalance,
			&i.AccruedInterest,
			&i.PaymentAmount,
			&i.DueDate,
			&i.PaymentDueDay,
			&i.IsOverdue,
			&i.LateFees,
			&i.DaysUntilDue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsByDebt = `-- name: ListPaymentsByDebt :many
SELECT id, debt_id, amount, payment_date, type, notes, principal_applied, interest_applied, payment_method, created_at
FROM payments_history
WHERE debt_id = $1
ORDER BY payment_date DESC
LIMIT $2 OFFSET $3
`

type ListPaymentsByDebtParams struct {
	DebtID uuid.UUID
	Limit  int32
	Offset int32
}

func (q *Queries) ListPaymentsByDebt(ctx context.Context, arg ListPaymentsByDebtParams) ([]PaymentsHistory, error) {
	rows, err := q.db.QueryContext(ctx, listPaymentsByDebt, arg.DebtID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentsHistory
	for rows.Next() {
		var i PaymentsHistory
		if err := rows.Scan(
			&i.ID,
			&i.DebtID,
			&i.Amount,
			&i.PaymentDate,
			&i.Type,
			&i.Notes,
			&i.PrincipalApplied,
			&i.InterestApplied,
			&i.PaymentMethod,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordPayment = `-- name: RecordPayment :one
INSERT INTO payments_history (
  debt_id, amount, payment_date, type,
  principal_applied, interest_applied,
  notes, payment_method
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, debt_id, amount, payment_date, type, notes, principal_applied, interest_applied, payment_method, created_at
`

type RecordPaymentParams struct {
	DebtID           uuid.UUID
	Amount           decimal.Decimal
	PaymentDate      time.Time
	Type             PaymentType
	PrincipalApplied decimal.Decimal
	InterestApplied  decimal.Decimal
	Notes            sql.NullString
	PaymentMethod    sql.NullString
}

func (q *Queries) RecordPayment(ctx context.Context, arg RecordPaymentParams) (PaymentsHistory, error) {
	row := q.db.QueryRowContext(ctx, recordPayment,
		arg.DebtID,
		arg.Amount,
		arg.PaymentDate,
		arg.Type,
		arg.PrincipalApplied,
		arg.InterestApplied,
		arg.Notes,
		arg.PaymentMethod,
	)
	var i PaymentsHistory
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.Amount,
		&i.PaymentDate,
		&i.Type,
		&i.Notes,
		&i.PrincipalApplied,
		&i.InterestApplied,
		&i.PaymentMethod,
		&i.CreatedAt,
	)
	return i, err
}
